version: '3.8'

services:
  corecalculator:
    build:
      context: ./CoreCalculator
      dockerfile: Dockerfile
    ports:
      - "52000:8080"
    networks:
      - my-network

  corefrontend:
    build:
      context: ./CoreFrontend
      dockerfile: Dockerfile
    ports:
      - "52001:80"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
    